version: '3'
services:
  api:
    build: "."
    ports:
      - "5001:80"
      - "5002:5000"
    environment:
      COOKBOOK_MONGO_ADDRESS: mongo:27017
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
