FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app-test

COPY ./run-tests.sh ./
COPY ./src ./

RUN dotnet restore ./ingredient-api.sln

RUN ["chmod", "+x", "/app-test/run-tests.sh"]
ENTRYPOINT ["/app-test/run-tests.sh"]