name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup-dotnetcore
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: dotnet-build
      run: dotnet build --configuration Release ./src/
