name: on-push

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/sdk:3.1.100-alpine
    steps:
    - uses: actions/checkout@v1
    - name: dotnet-build
      run: dotnet build -c Release ./src/
    - name: dotnet-test
      run: dotnet test -v=normal --no-build ./src/
