name: nightly

on:
  schedule:
    - cron: "0 0 * * *" # Run every night at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dotnet-build
      run: dotnet build --configuration Release ./src/
