name: nightly

on:
  schedule:
    - cron: "0 0 * * *" # Run every night at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: dotnetcore-setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: dotnet-build
      run: dotnet build --configuration Release
